In [65]:
from sklearn.preprocessing import Imputer
import pandas as pd
from sklearn.preprocessing import OneHotEncoder
import numpy as np

### 1.Imputer Используется для замены пропущенных значений, Хорошо сочетается с pipline!

In [3]:
# Заменить все НАН на средние по столбцу!

imr = Imputer(missing_values="NaN", strategy = "mean",axis=0)

In [ ]:
imr_data = imr.fit_transform(data)

### 2.Преобразуем Категориальны признаки!

In [35]:
df = pd.DataFrame([
    ['green','M',10.3,'target1'],
    ['blue','S',8.2,'target2'],
    ['red','X',14.3,'target1'],
])

In [37]:
df.columns =['Color','Size','Price','Target']


In [38]:
df

Color Size  Price   Target
0  green    M   10.3  target1
1   blue    S    8.2  target2
2    red    X   14.3  target1

In [39]:
size_mapping = {
    'M': 1,
    'S': 0,
    'X': 2
}

In [40]:
df['Size'] = df['Size'].map(size_mapping)

In [41]:
df

Color  Size  Price   Target
0  green     1   10.3  target1
1   blue     0    8.2  target2
2    red     2   14.3  target1

In [42]:
df['Target'] = df['Target'].apply(lambda x: 0 if x == 'target1' else 1 )

In [43]:
df

Color  Size  Price  Target
0  green     1   10.3       0
1   blue     0    8.2       1
2    red     2   14.3       0

### 3.OneHotEncoder реобазует категориальные числовые признаки в разреженную матрицу

In [53]:
one = OneHotEncoder(categorical_features = [0])
X = df[['Size','Price']].values

In [54]:
X

array([[ 1. , 10.3],
       [ 0. ,  8.2],
       [ 2. , 14.3]])

In [56]:
one.fit_transform(X).toarray()

array([[ 0. ,  1. ,  0. , 10.3],
       [ 1. ,  0. ,  0. ,  8.2],
       [ 0. ,  0. ,  1. , 14.3]])

###  4.getDummy для преобразования строковых  в числовые

In [57]:
df = pd.get_dummies(df)

In [58]:
df

Size  Price  Target  Color_blue  Color_green  Color_red
0     1   10.3       0           0            1          0
1     0    8.2       1           1            0          0
2     2   14.3       0           0            0          1

In [62]:
len([1, 2, 3])

3

In [63]:
['a'] * 4

['a', 'a', 'a', 'a']

In [66]:
np.array([0.] * 10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [67]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [71]:
np.random(10)

TypeError: 'module' object is not callable

In [70]:
np.random.random(1)

array([0.94994527])

In [72]:
df.info()

AttributeError: info not found